defmodule TrialApp.Reports do
  @moduledoc """
  The Reports context - handles PDF report generation and management.
  """

  import Ecto.Query, warn: false
  alias TrialApp.Repo
  alias TrialApp.Reports.Report
  alias TrialApp.Reports.PdfGenerator
  alias TrialApp.Eams

  # -------------------- CRUD OPERATIONS --------------------

  @doc """
  Lists all reports for a specific attachee.
  """
  def list_reports_for_attachee(attachee_id) do
    Report
    |> where([r], r.attachee_id == ^attachee_id)
    |> order_by([r], desc: r.inserted_at)
    |> preload([:generated_by])
    |> Repo.all()
  end

  @doc """
  Lists all reports generated by a specific supervisor/user.
  """
  def list_reports_by_generator(user_id) do
    Report
    |> where([r], r.generated_by_id == ^user_id)
    |> order_by([r], desc: r.inserted_at)
    |> preload([:attachee, attachee: :user])
    |> Repo.all()
  end

  @doc """
  Gets a single report.
  """
  def get_report!(id) do
    Report
    |> Repo.get!(id)
    |> Repo.preload([:attachee, :generated_by, attachee: [:user, :department, :organization]])
  end

  @doc """
  Creates a report record.
  """
  def create_report(attrs \\ %{}) do
    %Report{}
    |> Report.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a report.
  """
  def update_report(%Report{} = report, attrs) do
    report
    |> Report.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a report and its associated file.
  """
  def delete_report(%Report{} = report) do
    # Delete the file if it exists
    if report.file_path && File.exists?(report.file_path) do
      File.rm(report.file_path)
    end

    Repo.delete(report)
  end

  @doc """
  Marks a report as sent.
  """
  def mark_as_sent(%Report{} = report) do
    report
    |> Report.send_changeset()
    |> Repo.update()
  end

  @doc """
  Marks a report as viewed.

  FIX: This function's arity was changed from /1 to /2 to accept the
  timestamp passed from the LiveView, resolving the UndefinedFunctionError.
  """
  def mark_as_viewed(%Report{} = report, viewed_at \\ DateTime.utc_now()) do
    report
    # Use generic changeset to apply the `viewed_at` attribute
    |> Report.changeset(%{viewed_at: viewed_at})
    |> Repo.update()
  end

  # -------------------- REPORT GENERATION --------------------

  @doc """
  Generates a report for an attachee
  """
  def generate_attachee_report(attachee, generated_by, params) do
    with {:ok, start_date} <- parse_date(params["period_start"]),
         {:ok, end_date} <- parse_date(params["period_end"]),
         :ok <- validate_date_range(start_date, end_date) do

      # Create report record
      report_attrs = %{
        attachee_id: attachee.id,
        generated_by_id: generated_by.id,
        report_type: params["report_type"],
        period_start: start_date,
        period_end: end_date,
        status: "draft"
      }

      with {:ok, report} <- create_report(report_attrs),
           {:ok, report} <- generate_and_store_pdf(report, attachee) do
        {:ok, report}
      end
    end
  end

  @doc """
  Gets the file path for a report
  """
  def get_report_file_path(report) do
    report.file_path
  end

  # -------------------- PRIVATE HELPERS --------------------

  defp parse_date(date_string) when is_binary(date_string) do
    case Date.from_iso8601(date_string) do
      {:ok, date} -> {:ok, date}
      {:error, _} -> {:error, "Invalid date format"}
    end
  end

  defp parse_date(_), do: {:error, "Date is required"}

  defp validate_date_range(start_date, end_date) do
    if Date.compare(start_date, end_date) == :gt do
      {:error, "Start date must be before end date"}
    else
      :ok
    end
  end

  defp generate_and_store_pdf(report, attachee) do
    # Ensure directory exists
    ensure_reports_directory()

    # Generate filename
    filename = generate_filename(attachee, report.report_type)
    file_path = Path.join(reports_directory(), filename)

    # Gather report data
    report_data = gather_report_data(attachee.id)

    # Generate PDF
    case PdfGenerator.generate(report, report_data, file_path) do
      {:ok, _path} ->
        # Update report with file info
        update_report(report, %{
          file_name: filename,
          file_path: file_path
        })

      {:error, reason} ->
        # Clean up the report record if PDF generation fails
        delete_report(report)
        {:error, reason}
    end
  end

  # -------------------- REPORT DATA GATHERING --------------------

  @doc """
  Gathers all data needed for an evaluation report.
  """
  def gather_report_data(attachee_id) do
    attachee = Eams.get_attachee!(attachee_id, %{preloads: [:user, :department, :organization]})
    tasks = Eams.list_tasks_for_attachee(attachee_id)
    evaluations = Eams.list_evaluations_for_attachee(attachee_id, %{preloads: [:evaluator]})
    task_evaluations = Eams.list_task_evaluations_by_attachee(attachee_id, %{preloads: [:evaluator]})

    # Get projects
    projects = Eams.list_projects_for_attachee(attachee_id)

    # Calculate stats
    avg_score = Eams.get_average_evaluation_score(attachee_id)
    eval_count = Eams.count_evaluations_for_attachee(attachee_id)

    # Task stats
    total_tasks = length(tasks)
    completed_tasks = Enum.count(tasks, &(&1.status == "completed"))
    completion_rate = if total_tasks > 0, do: Float.round(completed_tasks * 100.0 / total_tasks, 1), else: 0.0

    # Build task scores map
    task_scores = build_task_scores_map(task_evaluations)

    %{
      attachee: attachee,
      tasks: tasks,
      evaluations: evaluations,
      task_evaluations: task_evaluations,
      task_scores: task_scores,
      projects: projects,
      stats: %{
        avg_score: avg_score,
        eval_count: eval_count,
        total_tasks: total_tasks,
        completed_tasks: completed_tasks,
        pending_tasks: Enum.count(tasks, &(&1.status == "pending")),
        submitted_tasks: Enum.count(tasks, &(&1.status == "submitted")),
        in_progress_tasks: Enum.count(tasks, &(&1.status == "in_progress")),
        completion_rate: completion_rate
      }
    }
  end

  defp build_task_scores_map(task_evaluations) do
    task_evaluations
    |> Enum.filter(fn eval -> eval.task_id != nil end)
    |> Enum.group_by(& &1.task_id)
    |> Enum.into(%{}, fn {task_id, evals} ->
      latest = Enum.max_by(evals, & &1.inserted_at)
      {task_id, %{score: latest.score, label: score_label(latest.score)}}
    end)
  end

  defp score_label(score) when score >= 81, do: "Excellent"
  defp score_label(score) when score >= 61, do: "Good"
  defp score_label(score) when score >= 41, do: "Satisfactory"
  defp score_label(_), do: "Needs Improvement"

  # -------------------- PDF STORAGE --------------------

  @doc """
  Returns the directory where reports are stored.
  """
  def reports_directory do
    Path.join([:code.priv_dir(:trial_app), "static", "reports"])
  end

  @doc """
  Ensures the reports directory exists.
  """
  def ensure_reports_directory do
    dir = reports_directory()
    unless File.exists?(dir) do
      File.mkdir_p!(dir)
    end
    dir
  end

  @doc """
  Generates a unique filename for a report.
  """
  def generate_filename(attachee, report_type) do
    timestamp = DateTime.utc_now() |> Calendar.strftime("%Y%m%d_%H%M%S")
    attachee_name = (attachee.user.username || attachee.user.email)
                    |> String.replace(~r/[^a-zA-Z0-9]/, "_")
                    |> String.slice(0, 20)

    "#{report_type}_#{attachee_name}_#{timestamp}.pdf"
  end
end
