defmodule TrialApp.Reports.PdfGenerator do
  @moduledoc """
  Generates beautiful PDF reports using pdf_generator (wkhtmltopdf).
  """
  require Logger

  # --- 1. THE ADAPTER ---
  def generate_pdf(report, assigns, options, file_path) do
    attachee = assigns.attachee

    # DEBUG LOGS
    Logger.info("=== PDF GENERATOR DEBUG ===")
    Logger.info("Attachee: #{attachee.id}")
    Logger.info("Tasks received: #{length(Map.get(assigns, :attachee_tasks, []))}")
    Logger.info("Evaluations received: #{length(Map.get(assigns, :general_evaluations, []))}")

    report_data = %{
      attachee: attachee,
      organization: attachee.organization,
      department: attachee.department,
      stats: Map.get(assigns, :attachee_stats, %{}),
      tasks: Map.get(assigns, :attachee_tasks, []),
      task_scores: Map.get(assigns, :task_scores, %{}),
      evaluations: Map.get(assigns, :general_evaluations, []),
      projects: Map.get(assigns, :attachee_projects, []),
      custom_comments: Map.get(options, :custom_comments, ""),
      # Pass include flags
      include_tasks: Map.get(options, :include_tasks, true),
      include_evaluations: Map.get(options, :include_evaluations, true),
      include_projects: Map.get(options, :include_projects, true),
      include_stats: Map.get(options, :include_stats, true),
      period_start: report.period_start,
      period_end: report.period_end
    }

    generate_pdf_from_html(report, report_data, file_path)
  end

  alias TrialApp.Reports.ReportHTML

  # --- 2. MAIN LOGIC ---
  def generate_pdf_from_html(report, report_data, file_path) do
    html = render_report_html(report, report_data)

    options = [
      page_size: "A4",
      margin_top: "15mm",
      margin_bottom: "15mm",
      margin_left: "15mm",
      margin_right: "15mm",
      footer_html: footer_html(),
      disable_smart_shrinking: true,
      print_media_type: true
    ]

    case PdfGenerator.generate_binary(html, options) do
      {:ok, pdf_binary} ->
        File.write!(file_path, pdf_binary)
        Logger.info("PDF generated successfully: #{file_path}")
        {:ok, file_path}

      {:ok, _filename, pdf_binary} when is_binary(pdf_binary) ->
        File.write!(file_path, pdf_binary)
        Logger.info("PDF generated successfully (tuple match): #{file_path}")
        {:ok, file_path}

      {:error, reason} ->
        Logger.error("PDF Generation failed: #{inspect(reason)}")
        {:error, "Failed to generate PDF: #{inspect(reason)}"}

      unexpected ->
        Logger.error("Unknown PDF Generator return format: #{inspect(unexpected)}")
        {:error, "Unknown PDF generation error (Check server logs)"}
    end
  end

  defp render_report_html(report, data) do
    title = get_report_title(report.report_type)
    user = data.attachee.user

    attachee_name =
      cond do
        user.first_name && user.last_name -> "#{user.first_name} #{user.last_name}"
        user.username -> user.username
        true -> user.email
      end

    filtered_tasks = filter_by_period(data.tasks, data.period_start, data.period_end)

    filtered_evals =
      filter_evaluations_by_period(data.evaluations, data.period_start, data.period_end)

    total_tasks = length(filtered_tasks)
    completed_count = Enum.count(filtered_tasks, &(&1.status == "completed"))

    comp_rate =
      if total_tasks > 0, do: Float.round(completed_count * 100.0 / total_tasks, 1), else: 0.0

    eval_count = length(filtered_evals)

    avg_score =
      if eval_count > 0 do
        total = Enum.reduce(filtered_evals, 0, fn e, acc -> (e.score || 0) + acc end)
        Float.round(total / eval_count, 1)
      else
        0.0
      end

    assigns = %{
      title: title,
      # Use ReportHTML's styles
      css: ReportHTML.pdf_styles(),
      organization: data.organization,
      period_start: report.period_start,
      period_end: report.period_end,
      attachee: data.attachee,
      department: data.department,
      attachee_name: attachee_name,
      include_stats: data.include_stats,
      avg_score: avg_score,
      eval_count: eval_count,
      total_tasks: total_tasks,
      comp_rate: comp_rate,
      include_projects: data.include_projects,
      projects: data.projects,
      include_tasks: data.include_tasks,
      filtered_tasks: filtered_tasks,
      task_scores: data.task_scores,
      include_evaluations: data.include_evaluations,
      filtered_evals: filtered_evals,
      custom_comments: data.custom_comments
    }

    Phoenix.Template.render_to_string(ReportHTML, "report", "html", assigns)
  end

  defp footer_html do
    """
    <div style="text-align:center; font-size:9px; color:#94a3b8; border-top:1px solid #e2e8f0; padding-top:10px;">
      Generated by Attachment Management System • Confidential • Page <span class="pageNumber"></span>
    </div>
    """
  end

  # --- HELPERS (Same as before) ---
  defp get_report_title("evaluation_summary"), do: "Evaluation Summary"
  defp get_report_title("monthly_report"), do: "Monthly Progress Report"
  defp get_report_title("final_report"), do: "Final Attachment Report"
  defp get_report_title(_), do: "Attachee Report"

  defp filter_by_period(tasks, period_start, period_end) do
    Enum.filter(tasks, fn task ->
      task_date = extract_date(task.inserted_at)

      if task_date,
        do:
          Date.compare(task_date, period_start) != :lt and
            Date.compare(task_date, period_end) != :gt,
        else: true
    end)
  end

  defp filter_evaluations_by_period(evaluations, period_start, period_end) do
    Enum.filter(evaluations, fn eval ->
      eval_date = extract_date(eval.inserted_at)

      if eval_date,
        do:
          Date.compare(eval_date, period_start) != :lt and
            Date.compare(eval_date, period_end) != :gt,
        else: true
    end)
  end

  defp extract_date(%NaiveDateTime{} = dt), do: NaiveDateTime.to_date(dt)
  defp extract_date(%DateTime{} = dt), do: DateTime.to_date(dt)
  defp extract_date(%Date{} = d), do: d
  defp extract_date(_), do: nil
end
